### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by doug-wade** [Ategon/Lemmy-Mega-Bot#12]
I'm getting the following stack when I attempt to start the bot

```shell
SQLITE_ERROR: no such table: posts
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseURL (/home/doug/workspace/Lemmy-Mega-Bot/node_modules/node-fetch/lib/index.js:1164:12)
    at new Request (/home/doug/workspace/Lemmy-Mega-Bot/node_modules/node-fetch/lib/index.js:1210:17)
    at /home/doug/workspace/Lemmy-Mega-Bot/node_modules/node-fetch/lib/index.js:1453:19
    at new Promise (<anonymous>)
    at LemmyHttp.fetch (/home/doug/workspace/Lemmy-Mega-Bot/node_modules/node-fetch/lib/index.js:1451:9)
    at LemmyHttp.fetch (/home/doug/workspace/Lemmy-Mega-Bot/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at LemmyHttp.<anonymous> (/home/doug/workspace/Lemmy-Mega-Bot/node_modules/lemmy-js-client/dist/http.js:876:90)
    at Generator.next (<anonymous>)
    at /home/doug/workspace/Lemmy-Mega-Bot/node_modules/lemmy-js-client/dist/http.js:8:71 {
  code: 'ERR_INVALID_URL',
  input: 'https://"lemmy.world" // The instance the bot account is in/api/v3/user/login'
}
```

You can see my full configuration [here](https://github.com/doug-wade/Lemmy-Mega-Bot/tree/sports-bot).

**Comment by doug-wade** [comment]
I figured it out! My `.env` file was misformatted. I had

```
LEMMY_INSTANCE="lemmy.world" // The instance the bot account is in/api/v3/user/login'
```

but instead I needed

```
LEMMY_INSTANCE=lemmy.world
```
