### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Vittelius** [Ategon/Lemmy-Mega-Bot#6]
I'm unable to setup the bot. When I run `node main.js`  I get the following error:

```
~/Lemmy-Mega-Bot/main.js:1
import LemmyBot from 'lemmy-bot';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by mjpc13** [comment]
If you want, you can use Docker, check [this PR](https://github.com/Ategon/Lemmy-Mega-Bot/pull/7) and you won't have these dependencies problems.
